controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
checkout:
    path: /api/checkout
    controller: App\Controller\CheckoutController::checkout
    methods: [POST]